# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_keyboard.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(1024, 768)
        Form.setStyleSheet("*\n"
"{\n"
"    font: 75 18pt;\n"
"}\n"
"#SoftKeyBoard\n"
"{\n"
"    background-color:rgba(153, 153, 153,127);\n"
"}\n"
"QPushButton \n"
"{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgb(67,63,59);\n"
"    border-radius: 7px;\n"
"}/*\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgb(127,122,117)\n"
"}*/\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(33,30,27);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_keyboard_ = QtWidgets.QWidget(Form)
        self.widget_keyboard_.setObjectName("widget_keyboard_")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_keyboard_)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.btn_esc_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_esc_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_esc_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_esc_.setObjectName("btn_esc_")
        self.horizontalLayout_32.addWidget(self.btn_esc_)
        self.btn_f1_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f1_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f1_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f1_.setObjectName("btn_f1_")
        self.horizontalLayout_32.addWidget(self.btn_f1_)
        self.btn_f2_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f2_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f2_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f2_.setObjectName("btn_f2_")
        self.horizontalLayout_32.addWidget(self.btn_f2_)
        self.btn_f3_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f3_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f3_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f3_.setObjectName("btn_f3_")
        self.horizontalLayout_32.addWidget(self.btn_f3_)
        self.btn_f4_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f4_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f4_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f4_.setObjectName("btn_f4_")
        self.horizontalLayout_32.addWidget(self.btn_f4_)
        self.btn_f5_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f5_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f5_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f5_.setObjectName("btn_f5_")
        self.horizontalLayout_32.addWidget(self.btn_f5_)
        self.btn_f6_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f6_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f6_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f6_.setObjectName("btn_f6_")
        self.horizontalLayout_32.addWidget(self.btn_f6_)
        self.btn_f7_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f7_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f7_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f7_.setObjectName("btn_f7_")
        self.horizontalLayout_32.addWidget(self.btn_f7_)
        self.btn_f8_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f8_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f8_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f8_.setObjectName("btn_f8_")
        self.horizontalLayout_32.addWidget(self.btn_f8_)
        self.btn_f9_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f9_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f9_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f9_.setObjectName("btn_f9_")
        self.horizontalLayout_32.addWidget(self.btn_f9_)
        self.btn_f10_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f10_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f10_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f10_.setObjectName("btn_f10_")
        self.horizontalLayout_32.addWidget(self.btn_f10_)
        self.btn_f11_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f11_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f11_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f11_.setObjectName("btn_f11_")
        self.horizontalLayout_32.addWidget(self.btn_f11_)
        self.btn_f12_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_f12_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_f12_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_f12_.setObjectName("btn_f12_")
        self.horizontalLayout_32.addWidget(self.btn_f12_)
        self.verticalLayout_3.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.btn_waveline = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_waveline.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_waveline.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_waveline.setObjectName("btn_waveline")
        self.horizontalLayout_25.addWidget(self.btn_waveline)
        self.num_1_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.num_1_.setMinimumSize(QtCore.QSize(30, 40))
        self.num_1_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_1_.setObjectName("num_1_")
        self.horizontalLayout_25.addWidget(self.num_1_)
        self.num_2_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.num_2_.setMinimumSize(QtCore.QSize(30, 40))
        self.num_2_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_2_.setObjectName("num_2_")
        self.horizontalLayout_25.addWidget(self.num_2_)
        self.num_3_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.num_3_.setMinimumSize(QtCore.QSize(30, 40))
        self.num_3_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_3_.setObjectName("num_3_")
        self.horizontalLayout_25.addWidget(self.num_3_)
        self.num_4_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.num_4_.setMinimumSize(QtCore.QSize(30, 40))
        self.num_4_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_4_.setObjectName("num_4_")
        self.horizontalLayout_25.addWidget(self.num_4_)
        self.num_5_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.num_5_.setMinimumSize(QtCore.QSize(30, 40))
        self.num_5_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_5_.setObjectName("num_5_")
        self.horizontalLayout_25.addWidget(self.num_5_)
        self.num_6_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.num_6_.setMinimumSize(QtCore.QSize(30, 40))
        self.num_6_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_6_.setObjectName("num_6_")
        self.horizontalLayout_25.addWidget(self.num_6_)
        self.num_7_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.num_7_.setMinimumSize(QtCore.QSize(30, 40))
        self.num_7_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_7_.setObjectName("num_7_")
        self.horizontalLayout_25.addWidget(self.num_7_)
        self.num_8_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.num_8_.setMinimumSize(QtCore.QSize(30, 40))
        self.num_8_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_8_.setObjectName("num_8_")
        self.horizontalLayout_25.addWidget(self.num_8_)
        self.num_9_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.num_9_.setMinimumSize(QtCore.QSize(30, 40))
        self.num_9_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_9_.setObjectName("num_9_")
        self.horizontalLayout_25.addWidget(self.num_9_)
        self.num_0_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.num_0_.setMinimumSize(QtCore.QSize(30, 40))
        self.num_0_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_0_.setObjectName("num_0_")
        self.horizontalLayout_25.addWidget(self.num_0_)
        self.btn_minus_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_minus_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_minus_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_minus_.setObjectName("btn_minus_")
        self.horizontalLayout_25.addWidget(self.btn_minus_)
        self.btn_plus_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_plus_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_plus_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_plus_.setObjectName("btn_plus_")
        self.horizontalLayout_25.addWidget(self.btn_plus_)
        self.btn_backspace_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_backspace_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_backspace_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_backspace_.setObjectName("btn_backspace_")
        self.horizontalLayout_25.addWidget(self.btn_backspace_)
        self.verticalLayout_3.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.btn_tab_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_tab_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_tab_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_tab_.setObjectName("btn_tab_")
        self.horizontalLayout_24.addWidget(self.btn_tab_)
        self.char_q_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_q_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_q_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_q_.setObjectName("char_q_")
        self.horizontalLayout_24.addWidget(self.char_q_)
        self.char_w_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_w_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_w_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_w_.setObjectName("char_w_")
        self.horizontalLayout_24.addWidget(self.char_w_)
        self.char_e_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_e_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_e_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_e_.setObjectName("char_e_")
        self.horizontalLayout_24.addWidget(self.char_e_)
        self.char_r_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_r_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_r_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_r_.setObjectName("char_r_")
        self.horizontalLayout_24.addWidget(self.char_r_)
        self.char_t_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_t_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_t_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_t_.setObjectName("char_t_")
        self.horizontalLayout_24.addWidget(self.char_t_)
        self.char_y_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_y_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_y_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_y_.setObjectName("char_y_")
        self.horizontalLayout_24.addWidget(self.char_y_)
        self.char_u_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_u_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_u_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_u_.setObjectName("char_u_")
        self.horizontalLayout_24.addWidget(self.char_u_)
        self.char_i_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_i_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_i_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_i_.setObjectName("char_i_")
        self.horizontalLayout_24.addWidget(self.char_i_)
        self.char_o_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_o_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_o_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_o_.setObjectName("char_o_")
        self.horizontalLayout_24.addWidget(self.char_o_)
        self.char_p_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_p_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_p_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_p_.setObjectName("char_p_")
        self.horizontalLayout_24.addWidget(self.char_p_)
        self.btn_left_bracket_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_left_bracket_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_left_bracket_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_left_bracket_.setObjectName("btn_left_bracket_")
        self.horizontalLayout_24.addWidget(self.btn_left_bracket_)
        self.btn_right_bracket_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_right_bracket_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_right_bracket_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_right_bracket_.setObjectName("btn_right_bracket_")
        self.horizontalLayout_24.addWidget(self.btn_right_bracket_)
        self.btn_slash_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_slash_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_slash_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_slash_.setObjectName("btn_slash_")
        self.horizontalLayout_24.addWidget(self.btn_slash_)
        self.verticalLayout_3.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btn_capslock_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_capslock_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_capslock_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_capslock_.setObjectName("btn_capslock_")
        self.horizontalLayout_23.addWidget(self.btn_capslock_)
        self.char_a_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_a_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_a_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_a_.setObjectName("char_a_")
        self.horizontalLayout_23.addWidget(self.char_a_)
        self.char_s_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_s_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_s_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_s_.setObjectName("char_s_")
        self.horizontalLayout_23.addWidget(self.char_s_)
        self.char_d_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_d_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_d_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_d_.setObjectName("char_d_")
        self.horizontalLayout_23.addWidget(self.char_d_)
        self.char_f_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_f_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_f_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_f_.setObjectName("char_f_")
        self.horizontalLayout_23.addWidget(self.char_f_)
        self.char_g_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_g_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_g_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_g_.setObjectName("char_g_")
        self.horizontalLayout_23.addWidget(self.char_g_)
        self.char_h_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_h_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_h_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_h_.setObjectName("char_h_")
        self.horizontalLayout_23.addWidget(self.char_h_)
        self.char_j_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_j_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_j_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_j_.setObjectName("char_j_")
        self.horizontalLayout_23.addWidget(self.char_j_)
        self.char_k_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_k_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_k_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_k_.setObjectName("char_k_")
        self.horizontalLayout_23.addWidget(self.char_k_)
        self.char_l_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_l_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_l_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_l_.setObjectName("char_l_")
        self.horizontalLayout_23.addWidget(self.char_l_)
        self.btn_semicolon_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_semicolon_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_semicolon_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_semicolon_.setObjectName("btn_semicolon_")
        self.horizontalLayout_23.addWidget(self.btn_semicolon_)
        self.btn_quota_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_quota_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_quota_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_quota_.setObjectName("btn_quota_")
        self.horizontalLayout_23.addWidget(self.btn_quota_)
        self.btn_enter_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_enter_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_enter_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_enter_.setObjectName("btn_enter_")
        self.horizontalLayout_23.addWidget(self.btn_enter_)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_shift_l_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_shift_l_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_shift_l_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_shift_l_.setObjectName("btn_shift_l_")
        self.horizontalLayout.addWidget(self.btn_shift_l_)
        self.char_z_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_z_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_z_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_z_.setObjectName("char_z_")
        self.horizontalLayout.addWidget(self.char_z_)
        self.char_x_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_x_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_x_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_x_.setObjectName("char_x_")
        self.horizontalLayout.addWidget(self.char_x_)
        self.char_c_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_c_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_c_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_c_.setObjectName("char_c_")
        self.horizontalLayout.addWidget(self.char_c_)
        self.char_v_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_v_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_v_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_v_.setObjectName("char_v_")
        self.horizontalLayout.addWidget(self.char_v_)
        self.char_b_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_b_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_b_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_b_.setObjectName("char_b_")
        self.horizontalLayout.addWidget(self.char_b_)
        self.char_n_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_n_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_n_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_n_.setObjectName("char_n_")
        self.horizontalLayout.addWidget(self.char_n_)
        self.char_m_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.char_m_.setMinimumSize(QtCore.QSize(30, 40))
        self.char_m_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_m_.setObjectName("char_m_")
        self.horizontalLayout.addWidget(self.char_m_)
        self.btn_comma_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_comma_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_comma_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_comma_.setObjectName("btn_comma_")
        self.horizontalLayout.addWidget(self.btn_comma_)
        self.btn_dot_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_dot_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_dot_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_dot_.setObjectName("btn_dot_")
        self.horizontalLayout.addWidget(self.btn_dot_)
        self.btn_backslash_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_backslash_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_backslash_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_backslash_.setObjectName("btn_backslash_")
        self.horizontalLayout.addWidget(self.btn_backslash_)
        self.btn_shift_r_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_shift_r_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_shift_r_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_shift_r_.setObjectName("btn_shift_r_")
        self.horizontalLayout.addWidget(self.btn_shift_r_)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.btn_ctrl_l_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_ctrl_l_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_ctrl_l_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_ctrl_l_.setObjectName("btn_ctrl_l_")
        self.horizontalLayout_22.addWidget(self.btn_ctrl_l_)
        self.btn_alt_l_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_alt_l_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_alt_l_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_alt_l_.setObjectName("btn_alt_l_")
        self.horizontalLayout_22.addWidget(self.btn_alt_l_)
        self.btn_space_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_space_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_space_.setMaximumSize(QtCore.QSize(300, 80))
        self.btn_space_.setText("")
        self.btn_space_.setObjectName("btn_space_")
        self.horizontalLayout_22.addWidget(self.btn_space_)
        self.btn_alt_r_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_alt_r_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_alt_r_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_alt_r_.setObjectName("btn_alt_r_")
        self.horizontalLayout_22.addWidget(self.btn_alt_r_)
        self.btn_ctrl_r_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_ctrl_r_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_ctrl_r_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_ctrl_r_.setObjectName("btn_ctrl_r_")
        self.horizontalLayout_22.addWidget(self.btn_ctrl_r_)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_21.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.btn_printscreen_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_printscreen_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_printscreen_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_printscreen_.setObjectName("btn_printscreen_")
        self.horizontalLayout_30.addWidget(self.btn_printscreen_)
        self.btn_scrolllock_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_scrolllock_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_scrolllock_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_scrolllock_.setObjectName("btn_scrolllock_")
        self.horizontalLayout_30.addWidget(self.btn_scrolllock_)
        self.btn_pause_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_pause_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_pause_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_pause_.setObjectName("btn_pause_")
        self.horizontalLayout_30.addWidget(self.btn_pause_)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.btn_insert_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_insert_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_insert_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_insert_.setObjectName("btn_insert_")
        self.horizontalLayout_29.addWidget(self.btn_insert_)
        self.btn_home_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_home_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_home_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_home_.setObjectName("btn_home_")
        self.horizontalLayout_29.addWidget(self.btn_home_)
        self.btn_pageup_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_pageup_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_pageup_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_pageup_.setObjectName("btn_pageup_")
        self.horizontalLayout_29.addWidget(self.btn_pageup_)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.btn_delete_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_delete_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_delete_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_delete_.setObjectName("btn_delete_")
        self.horizontalLayout_28.addWidget(self.btn_delete_)
        self.btn_end_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_end_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_end_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_end_.setObjectName("btn_end_")
        self.horizontalLayout_28.addWidget(self.btn_end_)
        self.btn_pagedown_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_pagedown_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_pagedown_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_pagedown_.setObjectName("btn_pagedown_")
        self.horizontalLayout_28.addWidget(self.btn_pagedown_)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_keyboard_)
        self.label_3.setMinimumSize(QtCore.QSize(40, 40))
        self.label_3.setMaximumSize(QtCore.QSize(80, 80))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.btn_up_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_up_.setMinimumSize(QtCore.QSize(30, 80))
        self.btn_up_.setMaximumSize(QtCore.QSize(16777215, 80))
        self.btn_up_.setObjectName("btn_up_")
        self.horizontalLayout_26.addWidget(self.btn_up_)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.btn_left_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_left_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_left_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_left_.setObjectName("btn_left_")
        self.horizontalLayout_27.addWidget(self.btn_left_)
        self.btn_down_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_down_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_down_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_down_.setObjectName("btn_down_")
        self.horizontalLayout_27.addWidget(self.btn_down_)
        self.btn_right_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_right_.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_right_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_right_.setObjectName("btn_right_")
        self.horizontalLayout_27.addWidget(self.btn_right_)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_21.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_2 = QtWidgets.QLabel(self.widget_keyboard_)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(80, 80))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_36.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.btn_numlock_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numlock_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numlock_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numlock_.setObjectName("btn_numlock_")
        self.horizontalLayout_35.addWidget(self.btn_numlock_)
        self.btn_divide_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_divide_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_divide_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_divide_.setObjectName("btn_divide_")
        self.horizontalLayout_35.addWidget(self.btn_divide_)
        self.btn_multiply_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_multiply_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_multiply_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_multiply_.setObjectName("btn_multiply_")
        self.horizontalLayout_35.addWidget(self.btn_multiply_)
        self.btn_subtract_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_subtract_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_subtract_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_subtract_.setObjectName("btn_subtract_")
        self.horizontalLayout_35.addWidget(self.btn_subtract_)
        self.verticalLayout.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.btn_numpad7_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numpad7_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numpad7_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numpad7_.setObjectName("btn_numpad7_")
        self.horizontalLayout_34.addWidget(self.btn_numpad7_)
        self.btn_numpad8_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numpad8_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numpad8_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numpad8_.setObjectName("btn_numpad8_")
        self.horizontalLayout_34.addWidget(self.btn_numpad8_)
        self.btn_numpad9_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numpad9_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numpad9_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numpad9_.setObjectName("btn_numpad9_")
        self.horizontalLayout_34.addWidget(self.btn_numpad9_)
        self.btn_add_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_add_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_add_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_add_.setObjectName("btn_add_")
        self.horizontalLayout_34.addWidget(self.btn_add_)
        self.verticalLayout.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.btn_numpad4_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numpad4_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numpad4_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numpad4_.setObjectName("btn_numpad4_")
        self.horizontalLayout_33.addWidget(self.btn_numpad4_)
        self.btn_numpad5_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numpad5_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numpad5_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numpad5_.setObjectName("btn_numpad5_")
        self.horizontalLayout_33.addWidget(self.btn_numpad5_)
        self.btn_numpad6_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numpad6_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numpad6_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numpad6_.setObjectName("btn_numpad6_")
        self.horizontalLayout_33.addWidget(self.btn_numpad6_)
        self.verticalLayout.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_numpad1_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numpad1_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numpad1_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numpad1_.setObjectName("btn_numpad1_")
        self.horizontalLayout_3.addWidget(self.btn_numpad1_)
        self.btn_numpad2_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numpad2_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numpad2_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numpad2_.setObjectName("btn_numpad2_")
        self.horizontalLayout_3.addWidget(self.btn_numpad2_)
        self.btn_numpad3_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numpad3_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numpad3_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numpad3_.setObjectName("btn_numpad3_")
        self.horizontalLayout_3.addWidget(self.btn_numpad3_)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.btn_numpad0_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_numpad0_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_numpad0_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_numpad0_.setObjectName("btn_numpad0_")
        self.horizontalLayout_31.addWidget(self.btn_numpad0_)
        self.btn_decimal_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_decimal_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_decimal_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_decimal_.setObjectName("btn_decimal_")
        self.horizontalLayout_31.addWidget(self.btn_decimal_)
        self.btn_return_ = QtWidgets.QPushButton(self.widget_keyboard_)
        self.btn_return_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_return_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_return_.setObjectName("btn_return_")
        self.horizontalLayout_31.addWidget(self.btn_return_)
        self.verticalLayout.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_21.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_keyboard_, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 12)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Input Panel"))
        self.btn_esc_.setText(_translate("Form", "Esc"))
        self.btn_f1_.setText(_translate("Form", "f1"))
        self.btn_f2_.setText(_translate("Form", "f2"))
        self.btn_f3_.setText(_translate("Form", "f3"))
        self.btn_f4_.setText(_translate("Form", "f4"))
        self.btn_f5_.setText(_translate("Form", "f5"))
        self.btn_f6_.setText(_translate("Form", "f6"))
        self.btn_f7_.setText(_translate("Form", "f7"))
        self.btn_f8_.setText(_translate("Form", "f8"))
        self.btn_f9_.setText(_translate("Form", "f9"))
        self.btn_f10_.setText(_translate("Form", "f10"))
        self.btn_f11_.setText(_translate("Form", "f11"))
        self.btn_f12_.setText(_translate("Form", "f12"))
        self.btn_waveline.setText(_translate("Form", "~"))
        self.num_1_.setText(_translate("Form", "!\n"
"1"))
        self.num_2_.setText(_translate("Form", "@\n"
"2"))
        self.num_3_.setText(_translate("Form", "#\n"
"3"))
        self.num_4_.setText(_translate("Form", "$\n"
"4"))
        self.num_5_.setText(_translate("Form", "%\n"
"5"))
        self.num_6_.setText(_translate("Form", "^\n"
"6"))
        self.num_7_.setText(_translate("Form", "&&\n"
"7"))
        self.num_8_.setText(_translate("Form", "*\n"
"8"))
        self.num_9_.setText(_translate("Form", "(\n"
"9"))
        self.num_0_.setText(_translate("Form", ")\n"
"0"))
        self.btn_minus_.setText(_translate("Form", "—\n"
"-"))
        self.btn_plus_.setText(_translate("Form", "+\n"
"="))
        self.btn_backspace_.setText(_translate("Form", "<--"))
        self.btn_tab_.setText(_translate("Form", "Tab"))
        self.char_q_.setText(_translate("Form", "q"))
        self.char_w_.setText(_translate("Form", "w"))
        self.char_e_.setText(_translate("Form", "e"))
        self.char_r_.setText(_translate("Form", "r"))
        self.char_t_.setText(_translate("Form", "t"))
        self.char_y_.setText(_translate("Form", "y"))
        self.char_u_.setText(_translate("Form", "u"))
        self.char_i_.setText(_translate("Form", "i"))
        self.char_o_.setText(_translate("Form", "o"))
        self.char_p_.setText(_translate("Form", "p"))
        self.btn_left_bracket_.setText(_translate("Form", "{\n"
"["))
        self.btn_right_bracket_.setText(_translate("Form", "}\n"
"]"))
        self.btn_slash_.setText(_translate("Form", "|\n"
"\\"))
        self.btn_capslock_.setText(_translate("Form", "Caps"))
        self.char_a_.setText(_translate("Form", "a"))
        self.char_s_.setText(_translate("Form", "s"))
        self.char_d_.setText(_translate("Form", "d"))
        self.char_f_.setText(_translate("Form", "f"))
        self.char_g_.setText(_translate("Form", "g"))
        self.char_h_.setText(_translate("Form", "h"))
        self.char_j_.setText(_translate("Form", "j"))
        self.char_k_.setText(_translate("Form", "k"))
        self.char_l_.setText(_translate("Form", "l"))
        self.btn_semicolon_.setText(_translate("Form", ":\n"
";"))
        self.btn_quota_.setText(_translate("Form", "\"\n"
"\'"))
        self.btn_enter_.setText(_translate("Form", "Enter"))
        self.btn_shift_l_.setText(_translate("Form", "Shift"))
        self.char_z_.setText(_translate("Form", "z"))
        self.char_x_.setText(_translate("Form", "x"))
        self.char_c_.setText(_translate("Form", "c"))
        self.char_v_.setText(_translate("Form", "v"))
        self.char_b_.setText(_translate("Form", "b"))
        self.char_n_.setText(_translate("Form", "n"))
        self.char_m_.setText(_translate("Form", "m"))
        self.btn_comma_.setText(_translate("Form", "<\n"
","))
        self.btn_dot_.setText(_translate("Form", ">\n"
"."))
        self.btn_backslash_.setText(_translate("Form", "?\n"
"/"))
        self.btn_shift_r_.setText(_translate("Form", "Shift"))
        self.btn_ctrl_l_.setText(_translate("Form", "Ctrl"))
        self.btn_alt_l_.setText(_translate("Form", "Alt"))
        self.btn_alt_r_.setText(_translate("Form", "Alt"))
        self.btn_ctrl_r_.setText(_translate("Form", "Ctrl"))
        self.btn_printscreen_.setText(_translate("Form", "Print"))
        self.btn_scrolllock_.setText(_translate("Form", "Scr"))
        self.btn_pause_.setText(_translate("Form", "Pau"))
        self.btn_insert_.setText(_translate("Form", "Ins"))
        self.btn_home_.setText(_translate("Form", "Home"))
        self.btn_pageup_.setText(_translate("Form", "PgUp"))
        self.btn_delete_.setText(_translate("Form", "Del"))
        self.btn_end_.setText(_translate("Form", "End"))
        self.btn_pagedown_.setText(_translate("Form", "PgDn"))
        self.btn_up_.setText(_translate("Form", "↑"))
        self.btn_left_.setText(_translate("Form", "←"))
        self.btn_down_.setText(_translate("Form", "↓"))
        self.btn_right_.setText(_translate("Form", "→"))
        self.btn_numlock_.setText(_translate("Form", "Num"))
        self.btn_divide_.setText(_translate("Form", "/"))
        self.btn_multiply_.setText(_translate("Form", "*"))
        self.btn_subtract_.setText(_translate("Form", "-"))
        self.btn_numpad7_.setText(_translate("Form", "7"))
        self.btn_numpad8_.setText(_translate("Form", "8"))
        self.btn_numpad9_.setText(_translate("Form", "9"))
        self.btn_add_.setText(_translate("Form", "+"))
        self.btn_numpad4_.setText(_translate("Form", "4"))
        self.btn_numpad5_.setText(_translate("Form", "5"))
        self.btn_numpad6_.setText(_translate("Form", "6"))
        self.btn_numpad1_.setText(_translate("Form", "1"))
        self.btn_numpad2_.setText(_translate("Form", "2"))
        self.btn_numpad3_.setText(_translate("Form", "3"))
        self.btn_numpad0_.setText(_translate("Form", "0"))
        self.btn_decimal_.setText(_translate("Form", "."))
        self.btn_return_.setText(_translate("Form", "Enter"))
        self.label.setText(_translate("Form", "Please enter three keys in the order: "))
